on: 
  push:
    branches:
      - main
name: 🚀 Deploy Plugin on push
jobs:
  web-deploy:
    name: 🎉 Deploy Plugin to Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: public_html/wp-content/plugins/dandelion-event-sync/
        protocol: ftps
        port: 21
